# -*- coding: utf-8 -*-
"""Project_Flask.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1KgURzn3YQNwqbkOsKOiPfggNCzTPh4Zk
"""

# -*- coding: utf-8 -*-
"""Project_Flask.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1tpx8-8gH-wFW5qBH9b3e7Bq6FBqU0SA4
"""

import numpy as np
import pickle
import pandas as pd
from flask import Flask, request, jsonify, render_template

app=Flask(__name__)
pickle_in = open("projects.pkl","rb")
logistic_model = pickle.load(pickle_in)

@app.route('/')
def home():
    return render_template('Project.html')


@app.route('/predict',methods=["POST"])
def predict():
    """
    For rendering results on HTML GUI
    """
    int_features = [x for x in request.form.values()]
    final_features = [np.array(int_features)]
    prediction = logistic_model.predict(final_features)
    #prediction = logistic_model.predict([[242.0,23.2,25.4,30.0,11.5200,4.0200]])
    return render_template('Project_Flask.html', prediction_text = 'THE Given News is   {}'.format(float(prediction)))

if __name__=='__main__':
    app.run()
